### ISSUE TITLE
When to get ICRA2024PaperList

### ISSUE THREAD

**Issue by CAN-Lee** [ryanbgriffiths/ICRA2023PaperList#1]
Hi, when could get ICRA2024PaperList? thanks

**Comment by ryanbgriffiths** [comment]
The list is scraped off the ICRA website so I have to wait until the papers are put up there first. 
I'm going to guess this will be around mid to late April.

**Comment by ryanbgriffiths** [comment]
ICRA 2024 List available [here](https://github.com/ryanbgriffiths/ICRA2024PaperList)

**Comment by CAN-Lee** [comment]
@ryanbgriffiths Really appreciate it. thank you
